<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "visibility"
 *
 * Auto generated by Extension Builder 2018-09-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FSC Visbility',
    'description' => 'FSC responsive visibility helper tool for content elements.',
    'category' => 'plugin',
    'author' => 'Joe Schäfer',
    'author_email' => 'j.schaefer@schaefer-webentwicklung.de',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.2.3',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
